export const algorithmTestSet = [
  {
    fcId: {
      $oid: "sjdaidjsodajidso",
    },
    type: "q",
    latestRecord: {
      tapResult: null,
      swipeResult: "know",
    },
    prevFactor: 0,
    prevInterval: 0,
    nextReview: new Date("2023-07-10"),
    _id: "sdjaidjsoajdisdjoajid",
    createdAt: {
      $date: new Date("2023-06-19"),
    },
    updatedAt: {
      $date: new Date("2023-07-10"),
    },
  },

  {
    fcId: {
      $oid: "sjdaidjsodajidso",
    },
    type: "q",
    latestRecord: {
      tapResult: null,
      swipeResult: "know",
    },
    prevFactor: 0,
    prevInterval: 0,
    nextReview: new Date("2023-07-10"),
    _id: "sdjaidjsoajdisdjoajid",
    createdAt: {
      $date: new Date("2023-06-19"),
    },
    updatedAt: {
      $date: new Date("2023-07-10"),
    },
  },
];

// All Know
export const evaluationSet1 = [
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 3,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 4,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 5,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 6,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 7,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 8,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 9,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 10,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 9,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 10,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 11,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
];

// Forget twice during
export const evaluationSet2 = [
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 4,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 5,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 6,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 7,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 8,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
];

// Forget once
export const evaluationSet3 = [
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 3,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 5,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 6,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 7,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 8,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 9,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
];

// With some OneMore and forget start forget
export const evaluationSet4 = [
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 0,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 1,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "oneMore",
    know: 2,
    forget: 1,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "oneMore",
    know: 2,
    forget: 1,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 2,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 3,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 4,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 5,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "oneMore",
    know: 5,
    forget: 2,
    oneMore: 3,
    noMore: 0,
  },
];

export const evaluationSet5 = [
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 1,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "oneMore",
    know: 2,
    forget: 1,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 3,
    forget: 1,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "forget",
    know: 3,
    forget: 2,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 4,
    forget: 2,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 5,
    forget: 2,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "know",
    know: 6,
    forget: 2,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "q",
    tapResult: null,
    swipeResult: "oneMore",
    know: 6,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
];

// All Answer Correct and Swipe Know
export const evaluationSet6 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 3,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 4,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 6,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 7,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 8,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 9,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 10,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
];

// Not Lying but got wrong one time
export const evaluationSet7 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 3,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 6,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 7,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 8,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 9,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
];

// Not lying but got wrong twice
export const evaluationSet8 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 5,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 6,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 7,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 8,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
];

// Some Lying with no OneMore
export const evaluationSet9 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 1,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "know",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "forget",
    know: 4,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 4,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "know",
    know: 6,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 7,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
];

// Still Some Lying without OneMore
export const evaluationSet10 = [
  {
    type: "m",
    tapResult: 2,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 1,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "know",
    know: 3,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "forget",
    know: 3,
    forget: 2,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "forget",
    know: 3,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "know",
    know: 4,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 3,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "forget",
    know: 5,
    forget: 4,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 6,
    forget: 4,
    oneMore: 0,
    noMore: 0,
  },
];

// No Lying Without OneMore
export const evaluationSet11 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 1,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 1,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "oneMore",
    know: 2,
    forget: 1,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "forget",
    know: 2,
    forget: 2,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "oneMore",
    know: 2,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 3,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 4,
    forget: 2,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "oneMore",
    know: 4,
    forget: 2,
    oneMore: 3,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 2,
    oneMore: 3,
    noMore: 0,
  },
];

// Lying With OneMore
export const evaluationSet12 = [
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 1,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 2,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "know",
    know: 3,
    forget: 0,
    oneMore: 0,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "oneMore",
    know: 3,
    forget: 0,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "forget",
    know: 3,
    forget: 1,
    oneMore: 1,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "oneMore",
    know: 3,
    forget: 1,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 0,
    swipeResult: "know",
    know: 4,
    forget: 1,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 5,
    forget: 1,
    oneMore: 2,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 2,
    swipeResult: "oneMore",
    know: 5,
    forget: 1,
    oneMore: 3,
    noMore: 0,
  },
  {
    type: "m",
    tapResult: 1,
    swipeResult: "know",
    know: 6,
    forget: 1,
    oneMore: 3,
    noMore: 0,
  },
];
